### ISSUE TITLE
MMM-Remote-Control doesn't work with docker installation

### ISSUE THREAD

**Issue by crimsonclyde** [Jopyth/MMM-Remote-Control#220]
Gosh this module is bliss!
Loved it instant even if it doesn't work for me.

I mean, this is not an issue, it's by design. But I would party hard if we can Frankenstein something together to make it work with Docker. 
The docker setup: https://gitlab.com/khassel/magicmirror
and used in the MagicMirrorOS which is mentioned on the main project site:
https://github.com/guysoft/MagicMirrorOS

**OK what happens?**
Module installation is easy and works out of the box.
1. cd /home/pi/magicmirror/mounts/modules
2. Do the git clone
3. Execute: docker-compose exec -it bash
4. cd /home/pi/magicmirror/modules/MMM-Remote-Control
5. npm install
6. Add it to your config file and voilà you can straight away see it on a different machine, since the whitelist is empty and the listener is set to 0.0.0.0. 

And here comes the problem. As soon as you try to use halt/restart/monitor control you end up with:

![image](https://user-images.githubusercontent.com/2612152/97713419-17c8a300-1ac0-11eb-8d47-b7eedd7179e3.png)

**What's the point?**
Well obviously the command is executed inside the docker container. Checked node_helper.js and found the line which sends the command to the system: It's simple "shutdown -h/r now". Looking deeper inside I checked the command right inside the container and received:

`docker exec -it mm bash
node@magicmirroros:/opt/magic_mirror$ sudo shutdown -h now
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host i`

Yes, true by design you don't want that a container can shut down the system. BUT ;( that's sad. Really this module would save me a lot of time diggin' around how to control a Pi with MQTT. 

**Question:**
Somebody knows how to deal with it. Yes I know it might be dangerous to let a container control your system. That's not the point. The point is - is there a way?

BUT all in all - great idea, nicely done. Thanks for contributing it to the community. 
I will try to find a solution, but I am not a JavaScript guy :) I have done one module and it felt like hell to me. To stupid maybe XD don't know but I don't get JavaScript. 

If you have something or a page or a link where to search I would try it.
Maybe there is a solution, and we can add the possibility to add a "docker=1/0" to this plugin. Or a workaround that would be a great thing.

Cheers and keep up your good work - Clyde

**Comment by ezeholz** [comment]
Hey! When you say that you use monitor, you're referring to turn on and off? In that case, you can change the commands with Custom Commands feature. 

Is every command not working? Or just Shutdown/Reset/Monitor?

Just to help you out, I'm working on some custom commands for Shutdown and Reboot, so you can change those inside config, to run what you really need to.

Cheers :D

**Comment by goldyfruit** [comment]
@crimsonclyde Docker needs to communicate with `systemd` on the host to perform this kind of action.
I guess you are using the `rpi.yml `, try to add this to the mount list:
```
/run/systemd/private:/run/systemd/private
```

Which based on this https://gitlab.com/khassel/magicmirror/-/blob/master/run/rpi.yml should become:
```
version: '3'

services:
  magicmirror:
    container_name: mm
    image: karsten13/magicmirror:latest
    ports:
      - "8080:8080"
    volumes:
      - ../mounts/config:/opt/magic_mirror/config
      - ../mounts/modules:/opt/magic_mirror/modules
      - ../mounts/css:/opt/magic_mirror/css
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /opt/vc:/opt/vc/:ro
      - /run/systemd/private:/run/systemd/private
    devices:
      - /dev/vchiq
    environment:
      LD_LIBRARY_PATH: /opt/vc/lib
      DISPLAY: unix:0.0
    network_mode: host
    shm_size: "128mb"
    restart: unless-stopped
    command: 
      - npm
      - run
      - start
```

**Comment by crimsonclyde** [comment]
### Update:

So far I was **not able** to get it to work. :/

1. Added /run/systemd/private to /home/pi/magicmirror/run/docker-compose.yml
Since docker-compose is the one used as far as I understood the system right. No luck

2. Added /sys/fs/cgroup to /home/pi/magicmirror/run/docker-compose.yml
No luck, same problem

3. Added cap_add: - SYS_PTRACE and - NET_ADMIN as well as - privileged=true to the docker-compose.yml file
No luck still same.

I just want to restart / stop the system since I want to use OpenHAB2 further on. 
Every time I try to reboot or halt the system, while inside the container, I get:

`node@magicmirroros:/opt/magic_mirror$ sudo shutdown -h now
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
Failed to talk to init daemon.`

Current state of my docker-compose.yml file:

`version: '3'

services:
  magicmirror:
    container_name: mm
    image: karsten13/magicmirror:latest
    ports:
      - "8080:8080"
    volumes:
      - ../mounts/config:/opt/magic_mirror/config
      - ../mounts/modules:/opt/magic_mirror/modules
      - ../mounts/css:/opt/magic_mirror/css
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /opt/vc:/opt/vc/:ro
      - /run/systemd/private:/run/systemd/private
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    cap_add:
      - SYS_PTRACE
      - NET_ADMIN
      - privileged=true
    devices:
      - /dev/vchiq
    environment:
      LD_LIBRARY_PATH: /opt/vc/lib
      DISPLAY: unix:0.0
    network_mode: host
    shm_size: "128mb"
    restart: unless-stopped
    command:
      - npm
      - run
      - start`

**Comment by ezeholz** [comment]
Hey! So I managed to search a few things, maybe [this link](https://askubuntu.com/questions/1049852/how-to-solve-system-has-not-been-booted-with-systemd-as-init-system-pid-1) would help you. If you still getting errors after checking that link, please tell me again and I'll search about it. :D

**Comment by ezeholz** [comment]
Okay, I managed to get some time to figured this out. Seems to me like the privileged tag it's not part of the caps that you can add, in other hand you'll have to put it into the command tag, figured out because of [this](https://github.com/zalando/zalenium/issues/1087).
If that's not working, and you keep those cap you already got, you could try using the ALL cap to see if there's any change at all.

**Comment by crimsonclyde** [comment]
Hey :)

thx for the help. But still experience the same problem. According to [this](https://docs.docker.com/compose/compose-file/compose-file-v2/) article privileged should be added like

`privileged: true`

I tried, doesn't work. Tried to run docker with sudo, restarted the container with sudo. I am running out of ideas :/ But I should close the "issue" here. Since it is not an issue with the plugin. Maybe it is more an of an "issue" with the concept of running MagicMirror in a docker container.

```
version: '3'

services:
  magicmirror:
    container_name: mm
    image: karsten13/magicmirror:latest
    ports:
      - "8080:8080"
    volumes:
      - ../mounts/config:/opt/magic_mirror/config
      - ../mounts/modules:/opt/magic_mirror/modules
      - ../mounts/css:/opt/magic_mirror/css
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /opt/vc:/opt/vc/:ro
      - /run/systemd/private:/run/systemd/private
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    cap_add:
      - ALL
    devices:
      - /dev/vchiq
    environment:
      LD_LIBRARY_PATH: /opt/vc/lib
      DISPLAY: unix:0.0
    network_mode: host
    shm_size: "128mb"
    restart: unless-stopped
    privileged: true
    command:
      - npm
      - run
      - start
````

**Comment by ezeholz** [comment]
And adding the privileged as you just did, still giving you the same error? Or it's a different one? Maybe it's not just Docker itself, but also MagicMirrorOS.
You can let the issue open, and we'll try to help you as long as we can. :D

**Comment by crimsonclyde** [comment]
@ezeholz 
Yes added privileged. The config is the one currently running (docker-compose.yml). The error is the exact same it always claims that the system is not booted with systemd.

```

**Comment by crimsonclyde** [comment]
@ezeholz
Yes added privileged. The config is the one currently running (docker-compose.yml). The error is the exact same it always claims that the system is not booted with systemd.

Here the commands and the output

```
docker exec -it mm bash
sudo shutdown -h now
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
```

Sorry closed it accidentally.

**Comment by ezeholz** [comment]
I believe that maybe there's a problem with using `docker exec` command and privileged, as I read in a post on StackOverflow. You could try using `docker run` instead, and adding the privileged flag right after the run. I think it's because [exec](https://docs.docker.com/engine/reference/commandline/exec/) create an instance of a command, and [run](https://docs.docker.com/engine/reference/commandline/run/) creates a container.

The problem here it's that privileged should start systemd with the container. If you can make the container run as privileged, you'll be able to do everything that's not actually working.

**Comment by goldyfruit** [comment]
I managed to reboot my RPi from a Docker container.
Two things were missing:
  - First, you need to pass D-Bus directory to your container
  - Second, you need to be into the same PID namespace than the host.

Try this:
```
version: '3'

services:
  magicmirror:
    container_name: mm
    image: karsten13/magicmirror:latest
    pid: "host"
    ports:
      - "8080:8080"
    volumes:
      - ../mounts/config:/opt/magic_mirror/config
      - ../mounts/modules:/opt/magic_mirror/modules
      - ../mounts/css:/opt/magic_mirror/css
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /opt/vc:/opt/vc/:ro
      - /run/dbus:/run/dbus
      - /run/systemd:/run/systemd
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    cap_add:
      - ALL
    devices:
      - /dev/vchiq
    environment:
      LD_LIBRARY_PATH: /opt/vc/lib
      DISPLAY: unix:0.0
    network_mode: host
    shm_size: "128mb"
    restart: unless-stopped
    privileged: true
    command:
      - npm
      - run
      - start
```
Again from a security perspective it's pretty bad but you seems to be aware of that so, so far so good :+1:

**Comment by crimsonclyde** [comment]
@goldyfruit 
Whoop Whoop where are getting somewhere. I changed docker-compose.yml and rpi.yml to your version which contains /run/dbus and pid: "host". And there we go we have access to systemctl. 

Tried to run sudo shutdown -r now inside the container
```
root@magicmirroros:/opt/magic_mirror# shutdown -r now
Running in chroot, ignoring request.
```

Am I missing something??

I know I am not really helpful, and I know it's not really safe doing all this :) I appreciate every single minute you all spent on a problem that's by design not a problem with the module itself.

**So everyone else out there trying this - you need to be aware of the problem itself that you can manipulate the host with such configs. Have a look at [this article](https://www.trendmicro.com/en_us/research/19/l/why-running-a-privileged-container-in-docker-is-a-bad-idea.html).**

**Comment by goldyfruit** [comment]
I'm not sure about this one, could you please try `reboot` or `reboot -f` ?

**Comment by crimsonclyde** [comment]
Maybe there is a solution with "SYSTEMD_IGNORE_CHROOT=yes" or "=1". But so far I was not able to get it to work with the yml file.

Let's give it a try!

```
    environment:
      LD_LIBRARY_PATH: /opt/vc/lib
      DISPLAY: unix:0.0
      SYSTEMD_IGNORE_CHROOT: 1
``` 
Which results after a reboot in a not starting container. Logs from docker:

mm             | ./entrypoint.sh: 81: exec: npmignore: not found
